Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\AdminController",
            "name": "AdminController",
            "summary": "Class\u0020AdminController\u0020\u002D\u0020current\u0020not\u0020used.",
            "url": "classes/App-Controller-AdminController.html"
        },                {
            "fqsen": "\\App\\Controller\\AdminController\u003A\u003AdashBoard\u0028\u0029",
            "name": "dashBoard",
            "summary": "",
            "url": "classes/App-Controller-AdminController.html#method_dashBoard"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController",
            "name": "FollowingController",
            "summary": "Class\u0020FollowingController",
            "url": "classes/App-Controller-FollowingController.html"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "FollowingController\u0020constructor.",
            "url": "classes/App-Controller-FollowingController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003AaddFollowingUser\u0028\u0029",
            "name": "addFollowingUser",
            "summary": "Endpoint\u0020to\u0020add\u0020new\u0020user\u0020to\u0020following\u0020users.",
            "url": "classes/App-Controller-FollowingController.html#method_addFollowingUser"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003AaddFollowingHashtag\u0028\u0029",
            "name": "addFollowingHashtag",
            "summary": "Endpoint\u0020to\u0020add\u0020new\u0020hashtag\u0020to\u0020following\u0020hashtags.",
            "url": "classes/App-Controller-FollowingController.html#method_addFollowingHashtag"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003AunFollowUser\u0028\u0029",
            "name": "unFollowUser",
            "summary": "Delete\u0020user\u0020from\u0020following\u0020users.",
            "url": "classes/App-Controller-FollowingController.html#method_unFollowUser"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003AunFollowHashtag\u0028\u0029",
            "name": "unFollowHashtag",
            "summary": "Delete\u0020hashtag\u0020from\u0020following\u0020hashtags.",
            "url": "classes/App-Controller-FollowingController.html#method_unFollowHashtag"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003A\u0024followingRepository",
            "name": "followingRepository",
            "summary": "",
            "url": "classes/App-Controller-FollowingController.html#property_followingRepository"
        },                {
            "fqsen": "\\App\\Controller\\FollowingController\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Controller-FollowingController.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Controller\\MainRouteController",
            "name": "MainRouteController",
            "summary": "Class\u0020MainRouteController",
            "url": "classes/App-Controller-MainRouteController.html"
        },                {
            "fqsen": "\\App\\Controller\\MainRouteController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "It\u0027s\u0020only\u0020for\u0020logout\u0020endpoint\u0020route.",
            "url": "classes/App-Controller-MainRouteController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController",
            "name": "MyOAuthAccessTokenController",
            "summary": "Class\u0020MyOAuthAccessTokenController",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MyOAuthAccessTokenController\u0020constructor.",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003AgenerateToken\u0028\u0029",
            "name": "generateToken",
            "summary": "This\u0020is\u0020function\u0020to\u0020generating\u0020new\u0020access\u0020token.\u0020Mandatory\u0020data\u003A\n\u002D\u0020client_id\u0020\u002810\u0020character\u0020string\u0029\n\u002D\u0020client_secret\u0020\u002820\u0020character\u0020string\u0029\n\u002D\u0020username\u0020\u0028email\u0029\n\u002D\u0020password\u0020\u0028without\u0020hash\u0029",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#method_generateToken"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "This\u0020is\u0020function\u0020for\u0020checking\u0020if\u0020the\u0020token\u0020is\u0020up\u002Dto\u002Ddate.\u0020Mandatory\u0020data\u003A\n\u002D\u0020identifier\u0020\u0028our\u0020token\u0020string\u0029",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#method_check"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003A\u0024myOAuthAccessTokenRepository",
            "name": "myOAuthAccessTokenRepository",
            "summary": "",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#property_myOAuthAccessTokenRepository"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003A\u0024myOAuthClient",
            "name": "myOAuthClient",
            "summary": "",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#property_myOAuthClient"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003A\u0024myUser",
            "name": "myUser",
            "summary": "",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#property_myUser"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthAccessTokenController\u003A\u003A\u0024loginFromAuthenticator",
            "name": "loginFromAuthenticator",
            "summary": "",
            "url": "classes/App-Controller-MyOAuthAccessTokenController.html#property_loginFromAuthenticator"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController",
            "name": "MyOAuthClientController",
            "summary": "Class\u0020MyOAuthClientController",
            "url": "classes/App-Controller-MyOAuthClientController.html"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MyOAuthClientController\u0020constructor.",
            "url": "classes/App-Controller-MyOAuthClientController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController\u003A\u003AmakeClient\u0028\u0029",
            "name": "makeClient",
            "summary": "This\u0020is\u0020function\u0020for\u0020creating\u0020new\u0020client\u0020on\u0020OAuth2\u0020Server.\u0020Mandatory\u0020data\u003A\n\u002D\u0020client_id\u0020\u0028ssl\u0020public\u0020key\u0029\n\u002D\u0020client_secret\u0020\u0028ssl\u0020private\u0020key\u0029\n\u002D\u0020name\u0020\u0028name\u0020of\u0020application\u0020\u002D\u0020string\u0029",
            "url": "classes/App-Controller-MyOAuthClientController.html#method_makeClient"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController\u003A\u003AupdateClient\u0028\u0029",
            "name": "updateClient",
            "summary": "This\u0020is\u0020function\u0020to\u0020update\u0020client\u0020Scope\u0020or\u0020Grant.\u0020Mandatory\u0020data\u003A\n\u002D\u0020client_id\u0020\u0028client_id\u0029\n\u002D\u0020grant\u0020\u0028string\u0020with\u0020space\u0020separator\u0020between\u0020grants\u0029\n\u002D\u0020scope\u0020\u0028string\u0020with\u0020space\u0020separator\u0020between\u0020scopes\u0029",
            "url": "classes/App-Controller-MyOAuthClientController.html#method_updateClient"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController\u003A\u003AdeActive\u0028\u0029",
            "name": "deActive",
            "summary": "This\u0020is\u0020function\u0020for\u0020deactivating\u0020the\u0020client.\u0020Mandatory\u0020data\u003A\n\u002D\u0020client_id\u0020\u0028public\u0020key\u0029\n\u002D\u0020client_secret\u0020\u0028private\u0020key\u0029",
            "url": "classes/App-Controller-MyOAuthClientController.html#method_deActive"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController\u003A\u003AmakeActive\u0028\u0029",
            "name": "makeActive",
            "summary": "This\u0020is\u0020function\u0020for\u0020activating\u0020the\u0020client.\u0020Mandatory\u0020data\u003A\n\u002D\u0020client_id\u0020\u0028public\u0020key\u0029\n\u002D\u0020client_secret\u0020\u0028private\u0020key\u0029",
            "url": "classes/App-Controller-MyOAuthClientController.html#method_makeActive"
        },                {
            "fqsen": "\\App\\Controller\\MyOAuthClientController\u003A\u003A\u0024myOAuthClientRepository",
            "name": "myOAuthClientRepository",
            "summary": "",
            "url": "classes/App-Controller-MyOAuthClientController.html#property_myOAuthClientRepository"
        },                {
            "fqsen": "\\App\\Controller\\PostController",
            "name": "PostController",
            "summary": "Class\u0020PostController",
            "url": "classes/App-Controller-PostController.html"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "This\u0020is\u0020endpoint\u0020function\u0020to\u0020adding\u0020new\u0020post.\u0020Mandatory\u0020data\u003A\n\u002D\u0020author\u0020\u0028user\u0020email\u0020\u002D\u0020string\u0029\n\u002D\u0020token\u0020\u0028access\u0020token\u0020\u002D\u0020string\u0029\n\u002D\u0020content\u0020\u0028post\u0020content\u0020\u002D\u0020string\u0029\n\u002D\u0020hashtags\u0020\u0028hashtag\u0020string\u0020with\u0020one\u0020space\u0020between\u0020hashtags\u0029",
            "url": "classes/App-Controller-PostController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003AshowMyPost\u0028\u0029",
            "name": "showMyPost",
            "summary": "This\u0020is\u0020endpoint\u0020function\u0020to\u0020show\u0020all\u0020user\u0027s\u0020post.\u0020Mandatory\u0020data\u003A\n\u002D\u0020token\u0020\u0028string\u0029\n\u002D\u0020author\u0020\u0020\u0028email\u0020\u002D\u0020string\u0029",
            "url": "classes/App-Controller-PostController.html#method_showMyPost"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003AshowUserPost\u0028\u0029",
            "name": "showUserPost",
            "summary": "This\u0020is\u0020endpoint\u0020function\u0020to\u0020show\u0020all\u0020user\u0027s\u0020post.\u0020Mandatory\u0020data\u003A\n\u002D\u0020token\u0020\u0028string\u0029\n\u002D\u0020wanted\u0020user\u0020\u0020\u0028email\u0020\u002D\u0020string\u0029\n\u002D\u0020username\u0020\u0028email\u0020\u002D\u0020string\u0029",
            "url": "classes/App-Controller-PostController.html#method_showUserPost"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003AshowMyFollow\u0028\u0029",
            "name": "showMyFollow",
            "summary": "This\u0020is\u0020endpoint\u0020function\u0020to\u0020show\u0020all\u0020following\u0020post\u0020\u0028by\u0020hashtags\u0020and\u0020users\u0029.\u0020Mandatory\u0020data\u003A\n\u002D\u0020token\u0020\u0028string\u0029\n\u002D\u0020username\u0020\u0028email\u0020\u002D\u0020string\u0029",
            "url": "classes/App-Controller-PostController.html#method_showMyFollow"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003AshowByHashtag\u0028\u0029",
            "name": "showByHashtag",
            "summary": "This\u0020is\u0020endpoint\u0020function\u0020to\u0020show\u0020all\u0020post\u0020with\u0020hashtag.\u0020Mandatory\u0020data\u003A\n\u002D\u0020username\u0020\u0028email\u0020\u002D\u0020string\u0029\n\u002D\u0020token\u0020\u0028string\u0029\n\u002D\u0020hashtag\u0020\u0028string\u0029",
            "url": "classes/App-Controller-PostController.html#method_showByHashtag"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#method_get"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#method_getAll"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#method_update"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003A\u0024postRepository",
            "name": "postRepository",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#property_postRepository"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003A\u0024myOAuthAccessTokenRepository",
            "name": "myOAuthAccessTokenRepository",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#property_myOAuthAccessTokenRepository"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Controller\\PostController\u003A\u003A\u0024followingRepository",
            "name": "followingRepository",
            "summary": "",
            "url": "classes/App-Controller-PostController.html#property_followingRepository"
        },                {
            "fqsen": "\\App\\Controller\\RegistrationController",
            "name": "RegistrationController",
            "summary": "Class\u0020RegistrationController",
            "url": "classes/App-Controller-RegistrationController.html"
        },                {
            "fqsen": "\\App\\Controller\\RegistrationController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RegistrationController\u0020constructor.",
            "url": "classes/App-Controller-RegistrationController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\RegistrationController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Function\u0020to\u0020register\u0020user\u0020by\u0020registe\u0020form\u0020\u002D\u0020not\u0020used.",
            "url": "classes/App-Controller-RegistrationController.html#method_register"
        },                {
            "fqsen": "\\App\\Controller\\RegistrationController\u003A\u003AverifyUserEmail\u0028\u0029",
            "name": "verifyUserEmail",
            "summary": "Function\u0020for\u0020send\u0020verify\u0020email.",
            "url": "classes/App-Controller-RegistrationController.html#method_verifyUserEmail"
        },                {
            "fqsen": "\\App\\Controller\\RegistrationController\u003A\u003AregisterUser\u0028\u0029",
            "name": "registerUser",
            "summary": "Endpoint\u0020for\u0020register\u0020new\u0020user.",
            "url": "classes/App-Controller-RegistrationController.html#method_registerUser"
        },                {
            "fqsen": "\\App\\Controller\\RegistrationController\u003A\u003A\u0024emailVerifier",
            "name": "emailVerifier",
            "summary": "",
            "url": "classes/App-Controller-RegistrationController.html#property_emailVerifier"
        },                {
            "fqsen": "\\App\\Controller\\RestController",
            "name": "RestController",
            "summary": "Class\u0020RestController",
            "url": "classes/App-Controller-RestController.html"
        },                {
            "fqsen": "\\App\\Controller\\RestController\u003A\u003AgetEndpoints\u0028\u0029",
            "name": "getEndpoints",
            "summary": "This\u0020is\u0020endpoint\u0020for\u0020listing\u0020all\u0020endpoints\u0020in\u0020my\u0020API.",
            "url": "classes/App-Controller-RestController.html#method_getEndpoints"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "Class\u0020SecurityController",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Function\u0020to\u0020login\u0020user\u0020in\u0020login\u0020form.\u0020\u002D\u0020not\u0020used.",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Endpoint\u0020to\u0020logout\u0020user.",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003AuserLogin\u0028\u0029",
            "name": "userLogin",
            "summary": "Endpoint\u0020for\u0020log\u0020in\u0020user.",
            "url": "classes/App-Controller-SecurityController.html#method_userLogin"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures",
            "name": "AppFixtures",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003A\u0024hashtags",
            "name": "hashtags",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#property_hashtags"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003A\u0024hashtags2",
            "name": "hashtags2",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#property_hashtags2"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003A\u0024postContent",
            "name": "postContent",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#property_postContent"
        },                {
            "fqsen": "\\App\\DataFixtures\\OAuthFixture",
            "name": "OAuthFixture",
            "summary": "",
            "url": "classes/App-DataFixtures-OAuthFixture.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\OAuthFixture\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-OAuthFixture.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\OAuthFixture\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "",
            "url": "classes/App-DataFixtures-OAuthFixture.html#property_identifier"
        },                {
            "fqsen": "\\App\\DataFixtures\\OAuthFixture\u003A\u003A\u0024secret",
            "name": "secret",
            "summary": "",
            "url": "classes/App-DataFixtures-OAuthFixture.html#property_secret"
        },                {
            "fqsen": "\\App\\DataFixtures\\OAuthFixture\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-DataFixtures-OAuthFixture.html#property_name"
        },                {
            "fqsen": "\\App\\DataFixtures\\OAuthFixture\u003A\u003A\u0024scopes",
            "name": "scopes",
            "summary": "",
            "url": "classes/App-DataFixtures-OAuthFixture.html#property_scopes"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture",
            "name": "UserFixture",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html#method___construct"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture\u003A\u003A\u0024passwordHasher",
            "name": "passwordHasher",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html#property_passwordHasher"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture\u003A\u003A\u0024firstNameArray",
            "name": "firstNameArray",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html#property_firstNameArray"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture\u003A\u003A\u0024lastNameArray",
            "name": "lastNameArray",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html#property_lastNameArray"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixture\u003A\u003A\u0024passwordArray",
            "name": "passwordArray",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixture.html#property_passwordArray"
        },                {
            "fqsen": "\\App\\Entity\\Following",
            "name": "Following",
            "summary": "Entity\u0020to\u0020store\u0020data\u0020about\u0020other\u0020users\u0020and\u0020hashtags\u0020followed\u0020by\u0020the\u0020currently\u0020logged\u0020in\u0020user.",
            "url": "classes/App-Entity-Following.html"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Following.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AgetUserEmail\u0028\u0029",
            "name": "getUserEmail",
            "summary": "Return\u0020the\u0020email\u0020of\u0020the\u0020user\u0020whose\u0020record\u0020this\u0020is.",
            "url": "classes/App-Entity-Following.html#method_getUserEmail"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AsetUserEmail\u0028\u0029",
            "name": "setUserEmail",
            "summary": "Give\u0020access\u0020to\u0020change\u0020the\u0020email\u0020of\u0020the\u0020user\u0020whose\u0020record\u0020this\u0020is.",
            "url": "classes/App-Entity-Following.html#method_setUserEmail"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AgetHashtags\u0028\u0029",
            "name": "getHashtags",
            "summary": "Return\u0020the\u0020string\u0020of\u0020hashtags\u0020following\u0020by\u0020user.\u0020Hashtags\u0020are\u0020separated\u0020by\u0020space.",
            "url": "classes/App-Entity-Following.html#method_getHashtags"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AsetHashtags\u0028\u0029",
            "name": "setHashtags",
            "summary": "Give\u0020access\u0020to\u0020change\u0020the\u0020hashtags\u0020string.",
            "url": "classes/App-Entity-Following.html#method_setHashtags"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AgetUsers\u0028\u0029",
            "name": "getUsers",
            "summary": "Return\u0020the\u0020string\u0020of\u0020users\u0020following\u0020by\u0020user.\u0020Users\u0020are\u0020separated\u0020by\u0020space.",
            "url": "classes/App-Entity-Following.html#method_getUsers"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003AsetUsers\u0028\u0029",
            "name": "setUsers",
            "summary": "Give\u0020access\u0020to\u0020change\u0020the\u0020users\u0020string.",
            "url": "classes/App-Entity-Following.html#method_setUsers"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Simply\u0020ID\u0020of\u0020user\u0020following\u0020data.",
            "url": "classes/App-Entity-Following.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003A\u0024user_email",
            "name": "user_email",
            "summary": "Email\u0020of\u0020individual\u0020users",
            "url": "classes/App-Entity-Following.html#property_user_email"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003A\u0024hashtags",
            "name": "hashtags",
            "summary": "Hashtags\u0020that\u0020are\u0020following\u0020by\u0020the\u0020user.",
            "url": "classes/App-Entity-Following.html#property_hashtags"
        },                {
            "fqsen": "\\App\\Entity\\Following\u003A\u003A\u0024users",
            "name": "users",
            "summary": "Other\u0020users\u0020that\u0020are\u0020following\u0020by\u0020the\u0020user.",
            "url": "classes/App-Entity-Following.html#property_users"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken",
            "name": "MyOAuthAccessToken",
            "summary": "Entity\u0020to\u0020store\u0020data\u0020about\u0020the\u0020access\u0020tokens\u0020that\u0020are\u0020generated\u0020by\u0020my\u0020OAuth\u0020Server\u0020implementation.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Return\u0020token\u0020ID.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetIdentifier\u0028\u0029",
            "name": "getIdentifier",
            "summary": "Return\u0020token\u0020string\u0020\u002820\u0020char\u0020string\u0029",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AsetIdentifier\u0028\u0029",
            "name": "setIdentifier",
            "summary": "Give\u0020access\u0020to\u0020change\u0020token.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_setIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetClientId\u0028\u0029",
            "name": "getClientId",
            "summary": "Return\u0020id\u0020of\u0020the\u0020client\u0020whose\u0020token\u0020it\u0020is.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getClientId"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AsetClientId\u0028\u0029",
            "name": "setClientId",
            "summary": "Give\u0020access\u0020to\u0020change\u0020client\u0020id.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_setClientId"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetMakeDate\u0028\u0029",
            "name": "getMakeDate",
            "summary": "Return\u0020the\u0020date\u0020when\u0020the\u0020token\u0020was\u0020generated.\u0020\u0028\u0027Y\u002DM\u002DD\u0020H\u002DM\u002DS\u0027\u0029",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getMakeDate"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AsetMakeDate\u0028\u0029",
            "name": "setMakeDate",
            "summary": "Give\u0020access\u0020to\u0020change\u0020date\u0020of\u0020generate\u0020the\u0020token.\u0020\u0028\u0027Y\u002DM\u002DD\u0020H\u002DM\u002DS\u0027\u0029",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_setMakeDate"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetUserId\u0028\u0029",
            "name": "getUserId",
            "summary": "Return\u0020id\u0020of\u0020the\u0020user\u0020whose\u0020token\u0020it\u0020is.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getUserId"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AsetUserId\u0028\u0029",
            "name": "setUserId",
            "summary": "Give\u0020access\u0020to\u0020change\u0020user\u0020email.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_setUserId"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetScopes\u0028\u0029",
            "name": "getScopes",
            "summary": "Return\u0020string\u0020of\u0020scopes.\u0020All\u0020scopes\u0020are\u0020separated\u0020by\u0020space.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getScopes"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AsetScopes\u0028\u0029",
            "name": "setScopes",
            "summary": "Give\u0020access\u0020to\u0020change\u0020scopes.\u0020Scopes\u0020are\u0020separated\u0020by\u0020space.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_setScopes"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AgetIsActive\u0028\u0029",
            "name": "getIsActive",
            "summary": "Return\u0020token\u0020active\u0020status.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_getIsActive"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003AsetIsActive\u0028\u0029",
            "name": "setIsActive",
            "summary": "Give\u0020access\u0020to\u0020change\u0020token\u0020status.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#method_setIsActive"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024id",
            "name": "id",
            "summary": "ID\u0020of\u0020given\u0020token.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "Token\u0020that\u0020is\u0020given\u0020by\u0020generateToken\u0020function.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_identifier"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024client_id",
            "name": "client_id",
            "summary": "Client\u0020identifier\u0020\u0028usually\u0020client\u0020public\u0020key\u0029.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_client_id"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024make_date",
            "name": "make_date",
            "summary": "Date\u0020when\u0020token\u0020was\u0020created.\u0020\u0028\u0027Y\u002DM\u002DD\u0020H\u002DM\u002DS\u0027\u0029",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_make_date"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024user_id",
            "name": "user_id",
            "summary": "User\u0020email\u0020for\u0020whom\u0020the\u0020token\u0020was\u0020created",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_user_id"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024scopes",
            "name": "scopes",
            "summary": "The\u0020scope\u0020of\u0020access\u0020to\u0020the\u0020specifying\u0020what\u0020actions\u0020the\u0020user\u0020can\u0020perform\u0020with\u0020this\u0020token.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_scopes"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthAccessToken\u003A\u003A\u0024is_active",
            "name": "is_active",
            "summary": "Variable\u0020which\u0020shows\u0020if\u0020token\u0020is\u0020up\u002Dto\u002Ddate.",
            "url": "classes/App-Entity-MyOAuthAccessToken.html#property_is_active"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient",
            "name": "MyOAuthClient",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetIdentifier\u0028\u0029",
            "name": "getIdentifier",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AsetIdentifier\u0028\u0029",
            "name": "setIdentifier",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_setIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetSecret\u0028\u0029",
            "name": "getSecret",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getSecret"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AsetSecret\u0028\u0029",
            "name": "setSecret",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_setSecret"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetIsActive\u0028\u0029",
            "name": "getIsActive",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getIsActive"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AsetIsActive\u0028\u0029",
            "name": "setIsActive",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_setIsActive"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetGrants\u0028\u0029",
            "name": "getGrants",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getGrants"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AsetGrants\u0028\u0029",
            "name": "setGrants",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_setGrants"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AgetScopes\u0028\u0029",
            "name": "getScopes",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_getScopes"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003AsetScopes\u0028\u0029",
            "name": "setScopes",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#method_setScopes"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024identifier",
            "name": "identifier",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_identifier"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024secret",
            "name": "secret",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_secret"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024grants",
            "name": "grants",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_grants"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024scopes",
            "name": "scopes",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_scopes"
        },                {
            "fqsen": "\\App\\Entity\\MyOAuthClient\u003A\u003A\u0024is_active",
            "name": "is_active",
            "summary": "",
            "url": "classes/App-Entity-MyOAuthClient.html#property_is_active"
        },                {
            "fqsen": "\\App\\Entity\\Post",
            "name": "Post",
            "summary": "Entity\u0020to\u0020store\u0020data\u0020about\u0020the\u0020user\u0027s\u0020posts.",
            "url": "classes/App-Entity-Post.html"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Return\u0020id\u0020of\u0020post.",
            "url": "classes/App-Entity-Post.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Return\u0020all\u0020content\u0020of\u0020post.",
            "url": "classes/App-Entity-Post.html#method_getContent"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Give\u0020access\u0020to\u0020change\u0020post\u0020content.",
            "url": "classes/App-Entity-Post.html#method_setContent"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AgetAuthor\u0028\u0029",
            "name": "getAuthor",
            "summary": "Return\u0020author\u0020of\u0020post.",
            "url": "classes/App-Entity-Post.html#method_getAuthor"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AsetAuthor\u0028\u0029",
            "name": "setAuthor",
            "summary": "Give\u0020access\u0020to\u0020change\u0020author\u0020of\u0020post\u0020ID.",
            "url": "classes/App-Entity-Post.html#method_setAuthor"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AgetHashtags\u0028\u0029",
            "name": "getHashtags",
            "summary": "Return\u0020hashtags\u0020string.",
            "url": "classes/App-Entity-Post.html#method_getHashtags"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AsetHashtags\u0028\u0029",
            "name": "setHashtags",
            "summary": "Give\u0020access\u0020to\u0020change\u0020hashtag\u0020string.",
            "url": "classes/App-Entity-Post.html#method_setHashtags"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Return\u0020all\u0020info\u0020about\u0020all\u0020posts.",
            "url": "classes/App-Entity-Post.html#method_toArray"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Id\u0020of\u0020post.",
            "url": "classes/App-Entity-Post.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003A\u0024content",
            "name": "content",
            "summary": "Content\u0020of\u0020post.",
            "url": "classes/App-Entity-Post.html#property_content"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003A\u0024author",
            "name": "author",
            "summary": "Author\u0020of\u0020post.",
            "url": "classes/App-Entity-Post.html#property_author"
        },                {
            "fqsen": "\\App\\Entity\\Post\u003A\u003A\u0024hashtags",
            "name": "hashtags",
            "summary": "String\u0020with\u0020hashtags.",
            "url": "classes/App-Entity-Post.html#property_hashtags"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "Entity\u0020to\u0020store\u0020data\u0020about\u0020the\u0020users.",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Return\u0020id\u0020of\u0020user.",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "Return\u0020email\u0020of\u0020user.",
            "url": "classes/App-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "Give\u0020access\u0020to\u0020set\u0020user\u0020email.",
            "url": "classes/App-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetFirstName\u0028\u0029",
            "name": "getFirstName",
            "summary": "Return\u0020user\u0020first\u0020name.",
            "url": "classes/App-Entity-User.html#method_getFirstName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetFirstName\u0028\u0029",
            "name": "setFirstName",
            "summary": "Give\u0020access\u0020to\u0020change\u0020user\u0020first\u0020name.",
            "url": "classes/App-Entity-User.html#method_setFirstName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetLastName\u0028\u0029",
            "name": "getLastName",
            "summary": "Return\u0020user\u0020last\u0020name.",
            "url": "classes/App-Entity-User.html#method_getLastName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetLastName\u0028\u0029",
            "name": "setLastName",
            "summary": "Give\u0020access\u0020to\u0020change\u0020user\u0020last\u0020name.",
            "url": "classes/App-Entity-User.html#method_setLastName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "A\u0020visual\u0020identifier\u0020that\u0020represents\u0020this\u0020user.",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "This\u0020method\u0020can\u0020be\u0020removed\u0020in\u0020Symfony\u00206.0\u0020\u002D\u0020is\u0020not\u0020needed\u0020for\u0020apps\u0020that\u0020do\u0020not\u0020check\u0020user\u0020passwords.",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetSalt\u0028\u0029",
            "name": "getSalt",
            "summary": "This\u0020method\u0020can\u0020be\u0020removed\u0020in\u0020Symfony\u00206.0\u0020\u002D\u0020is\u0020not\u0020needed\u0020for\u0020apps\u0020that\u0020do\u0020not\u0020check\u0020user\u0020passwords.",
            "url": "classes/App-Entity-User.html#method_getSalt"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024isVerified",
            "name": "isVerified",
            "summary": "Variable\u0020for\u0020checking\u0020that\u0020user\u0020is\u0020Verified\u0020\u0028email\u0020link\u0029.",
            "url": "classes/App-Entity-User.html#property_isVerified"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetIsVerified\u0028\u0029",
            "name": "setIsVerified",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setIsVerified"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AisAdmin\u0028\u0029",
            "name": "isAdmin",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_isAdmin"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AROLE_ADMIN",
            "name": "ROLE_ADMIN",
            "summary": "",
            "url": "classes/App-Entity-User.html#constant_ROLE_ADMIN"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "ID\u0020of\u0020user.",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "User\u0020email",
            "url": "classes/App-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "Roles\u0020like\u0020ROLE_ADMIN\u0020or\u0020sth\u0020else.",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024firstName",
            "name": "firstName",
            "summary": "User\u0020first\u0020name.",
            "url": "classes/App-Entity-User.html#property_firstName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024lastName",
            "name": "lastName",
            "summary": "User\u0020last\u0020name.",
            "url": "classes/App-Entity-User.html#property_lastName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "User\u0020hashed\u0020password.",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Form\\RegistrationFormType",
            "name": "RegistrationFormType",
            "summary": "",
            "url": "classes/App-Form-RegistrationFormType.html"
        },                {
            "fqsen": "\\App\\Form\\RegistrationFormType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-RegistrationFormType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\RegistrationFormType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-RegistrationFormType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository",
            "name": "FollowingRepository",
            "summary": "Repository\u0020for\u0020Following\u0020entity.",
            "url": "classes/App-Repository-FollowingRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "FollowingRepository\u0020constructor.",
            "url": "classes/App-Repository-FollowingRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository\u003A\u003AaddUser\u0028\u0029",
            "name": "addUser",
            "summary": "Function\u0020to\u0020put\u0020new\u0020Following\u0020Users\u0020to\u0020the\u0020record.",
            "url": "classes/App-Repository-FollowingRepository.html#method_addUser"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository\u003A\u003AaddHashtag\u0028\u0029",
            "name": "addHashtag",
            "summary": "Function\u0020to\u0020put\u0020new\u0020Following\u0020Hashtags\u0020to\u0020the\u0020record.",
            "url": "classes/App-Repository-FollowingRepository.html#method_addHashtag"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository\u003A\u003AdeleteUser\u0028\u0029",
            "name": "deleteUser",
            "summary": "Function\u0020to\u0020delete\u0020user\u0020from\u0020following\u0020user.",
            "url": "classes/App-Repository-FollowingRepository.html#method_deleteUser"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository\u003A\u003AdeleteHashtag\u0028\u0029",
            "name": "deleteHashtag",
            "summary": "Function\u0020to\u0020delete\u0020hashtag\u0020from\u0020following\u0020hashtags.",
            "url": "classes/App-Repository-FollowingRepository.html#method_deleteHashtag"
        },                {
            "fqsen": "\\App\\Repository\\FollowingRepository\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/App-Repository-FollowingRepository.html#property_manager"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository",
            "name": "MyOAuthAccessTokenRepository",
            "summary": "Repository\u0020for\u0020OAuth\u0020Access\u0020Token\u0020Repository.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MyOAuthAccessTokenRepository\u0020constructor.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AgenerateToken\u0028\u0029",
            "name": "generateToken",
            "summary": "Function\u0020to\u0020generate\u0020token\u0020string.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_generateToken"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AsetAccess\u0028\u0029",
            "name": "setAccess",
            "summary": "Function\u0020which\u0020generate\u0020new\u0020token\u0020record.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_setAccess"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AgetTokenScope\u0028\u0029",
            "name": "getTokenScope",
            "summary": "Return\u0020the\u0020token\u0020access\u0020scopes\u0020string.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_getTokenScope"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AisExistToken\u0028\u0029",
            "name": "isExistToken",
            "summary": "Checks\u0020if\u0020the\u0020token\u0020exist.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_isExistToken"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AcheckTokenTerm\u0028\u0029",
            "name": "checkTokenTerm",
            "summary": "Checks\u0020if\u0020the\u0020token\u0020term\u0020is\u0020up\u002Dto\u002Ddate.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_checkTokenTerm"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AcheckTokenUser\u0028\u0029",
            "name": "checkTokenUser",
            "summary": "Checks\u0020if\u0020user\u0020is\u0020owner\u0020of\u0020token.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_checkTokenUser"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003AcheckScope\u0028\u0029",
            "name": "checkScope",
            "summary": "Checks\u0020if\u0020the\u0020given\u0020scope\u0020is\u0020in\u0020the\u0020scopes.",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#method_checkScope"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthAccessTokenRepository\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/App-Repository-MyOAuthAccessTokenRepository.html#property_manager"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository",
            "name": "MyOAuthClientRepository",
            "summary": "Repository\u0020for\u0020OAuth\u0020Client\u0020Repository.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MyOAuthClientRepository\u0020constructor.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AsaveClient\u0028\u0029",
            "name": "saveClient",
            "summary": "Function\u0020which\u0020generate\u0020new\u0020client.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_saveClient"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AclientExist\u0028\u0029",
            "name": "clientExist",
            "summary": "Check\u0020if\u0020the\u0020client\u0020exist.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_clientExist"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AcheckSecret\u0028\u0029",
            "name": "checkSecret",
            "summary": "ATTENTION\u003A\u0020IDK\u0020WHAT\u0020IS\u0020THIS\u0020\u003A\u0028",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_checkSecret"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AupdateParameters\u0028\u0029",
            "name": "updateParameters",
            "summary": "Function\u0020to\u0020update\u0020grant\u0020and\u0020scopes.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_updateParameters"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AdeActive\u0028\u0029",
            "name": "deActive",
            "summary": "Function\u0020to\u0020client\u0020deactivation.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_deActive"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AupActive\u0028\u0029",
            "name": "upActive",
            "summary": "Function\u0020to\u0020make\u0020client\u0020active.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_upActive"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003AcheckClient\u0028\u0029",
            "name": "checkClient",
            "summary": "Function\u0020to\u0020validate\u0020client\u0020data.",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#method_checkClient"
        },                {
            "fqsen": "\\App\\Repository\\MyOAuthClientRepository\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/App-Repository-MyOAuthClientRepository.html#property_manager"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository",
            "name": "PostRepository",
            "summary": "Repository\u0020for\u0020Post\u0020Repository",
            "url": "classes/App-Repository-PostRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PostRepository\u0020constructor.",
            "url": "classes/App-Repository-PostRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003AsavePost\u0028\u0029",
            "name": "savePost",
            "summary": "Function\u0020which\u0020generate\u0020new\u0020post.",
            "url": "classes/App-Repository-PostRepository.html#method_savePost"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003AupdatePost\u0028\u0029",
            "name": "updatePost",
            "summary": "Function\u0020to\u0020update\u0020post.",
            "url": "classes/App-Repository-PostRepository.html#method_updatePost"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003AremovePost\u0028\u0029",
            "name": "removePost",
            "summary": "Function\u0020to\u0020delete\u0020post.",
            "url": "classes/App-Repository-PostRepository.html#method_removePost"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003AgetPosts\u0028\u0029",
            "name": "getPosts",
            "summary": "Function\u0020to\u0020get\u0020posts\u0020by\u0020author.",
            "url": "classes/App-Repository-PostRepository.html#method_getPosts"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003AgetPostByHash\u0028\u0029",
            "name": "getPostByHash",
            "summary": "Function\u0020to\u0020get\u0020posts\u0020by\u0020hashtag.",
            "url": "classes/App-Repository-PostRepository.html#method_getPostByHash"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003AgetByFollowingProperties\u0028\u0029",
            "name": "getByFollowingProperties",
            "summary": "Function\u0020to\u0020get\u0020all\u0020post\u0020by\u0020following\u0020users\u0020and\u0020hashtags.",
            "url": "classes/App-Repository-PostRepository.html#method_getByFollowingProperties"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/App-Repository-PostRepository.html#property_manager"
        },                {
            "fqsen": "\\App\\Repository\\PostRepository\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Repository-PostRepository.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "Repository\u0020for\u0020User\u0020Repository.",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method_findByEmail"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier",
            "name": "EmailVerifier",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003AsendEmailConfirmation\u0028\u0029",
            "name": "sendEmailConfirmation",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#method_sendEmailConfirmation"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003AhandleEmailConfirmation\u0028\u0029",
            "name": "handleEmailConfirmation",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#method_handleEmailConfirmation"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A\u0024verifyEmailHelper",
            "name": "verifyEmailHelper",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#property_verifyEmailHelper"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A\u0024mailer",
            "name": "mailer",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#property_mailer"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator",
            "name": "LoginFormAuthenticator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "LoginFormAuthenticator\u0020constructor.",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AcheckCredentials\u0028\u0029",
            "name": "checkCredentials",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_checkCredentials"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024passwordEncoder",
            "name": "passwordEncoder",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_passwordEncoder"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
