index:
    path: /
    controller: App\Controller\MainRouteController::mainpage

#route to logout page
app_logout:
    path: /logout
    methods: GET

oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'